apiVersion: v1
kind: Template
labels:
  template: keycloak
metadata:
  annotations:
    description: |-
      Keycloak authetication provider
    openshift.io/display-name: Keycloak
    tags: Keycloak
  name: "keycloak"

objects:

############
# DeploymentConfig : Keycloak
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: keycloak
      application: keycloak
    name: keycloak
  spec:
    replicas: 1
    selector:
      deploymentConfig: keycloak
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: keycloak
          deploymentConfig: keycloak
        name: keycloak
      spec:
        containers:
          - env:
              - name: KEYCLOAK_USER
                value: admin
              - name: KEYCLOAK_PASSWORD
                value: admin
              - name: DB_VENDOR
                value: MYSQL
              - name: JGROUPS_DISCOVERY_PROTOCOL
                value: dns.DNS_PING
              - name: JGROUPS_DISCOVERY_PROPERTIES
                value: keycloak.${NAMESPACE}.svc.cluster.local
              - name: DB_ADDR
                value: ${DB_HOST}
              - name: DB_DATABASE
                valueFrom:
                  secretKeyRef:
                    key: database-name
                    name: mariadb
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    key: database-user
                    name: mariadb
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: database-password
                    name: mariadb
            image: jboss/keycloak:4.8.3.Final
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /auth/realms/master
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 600
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            name: keycloak
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                name: https
                protocol: TCP
            readinessProbe:
              failureThreshold: 10
              httpGet:
                path: /auth/realms/master
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 5
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
              requests:
                cpu: '200m'
                memory: 512Mi
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /etc/x509/https
                name: keycloak-tls
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: keycloak-tls
            secret:
              defaultMode: 420
              secretName: ${TLS_SECRET}
    triggers:
      - type: ConfigChange




parameters:
- description: The OpenShift Namespace to use for autodiscovery
  displayName: Namespace
  name: NAMESPACE
  required: true
- description: Secret name to database settings
  displayName: Database Secret
  name: DB_SECRET
  required: true
  value: mariadb
- description: Database Host address
  displayName: Database Host
  name: DB_HOST
  required: true
  value: mariadb
- description: Secret name to TLS certificate
  displayName: TLS Secret
  name: TLS_SECRET
  required: true
  value: secure-keycloak